import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from '@/components/Footer'; // Import Footer

const Wotfard = localFont({
  src: "./fonts/wotfard.woff2",
  variable: "--font-wotfard",
  weight: "100 900",
});

const Cartograph = localFont({
  src: "./fonts/cartograph-regular-italic.woff2",
  variable: "--font-cartograph",
  weight: "100 900",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Wotfard.variable} ${Cartograph.variable} antialiased min-h-screen p-8 md:p-24`}
      >
        {children}
        <div className="max-w-2xl mx-auto">
        <hr className=" border-t border-gray-400" />
        <Footer /> {/* Include Footer here */}
        </div>
      </body>
    </html>
  );
}
